job: Validate job.OneShot name
cilium/hive pull request #10
Opened 2024-09-06 09:43 UTC by ovidiutirla

Adds validation for job.OneShot to match regex `^[a-z][a-z0-9_\-]{0,30}$`. It avoids construction of jobs that are not usable for metrics.

2024-09-06 09:43 UTC, ovidiutirla commented
/cc @joamaki

2024-09-09 07:47 UTC, joamaki approved these changes

2024-09-09 07:48 UTC, joamaki requested changes
We should do the same for all job types (Timer, Observer).

2024-09-09 08:34 UTC, ovidiutirla commented
> We should do the same for all job types (Timer, Observer).

Would you prefer to extract the fn as an common interface to avoid the `fn==nil` as argument?

2024-09-09 08:48 UTC, joamaki commented
> > We should do the same for all job types (Timer, Observer).
> 
> Would you prefer to extract the fn as an common interface to avoid the `fn==nil` as argument?

”fn” is very specific to the job type and I can imagine we’d at some point have jobs that don’t take an ”fn”. I’d keep the ”fn” validation in the job constructor itself.

2024-09-10 06:36 UTC, joamaki approved these changes

2024-09-10 06:36 UTC, merged

2024-09-11 20:01 UTC, ovidiutirla commented
The max job name was bumped to 100. https://github.com/cilium/hive/pull/14